// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar'];
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    AComment: typeof import('ant-design-vue/es')['Comment'];
    ADivider: typeof import('ant-design-vue/es')['Divider'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AList: typeof import('ant-design-vue/es')['List'];
    AListItem: typeof import('ant-design-vue/es')['ListItem'];
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta'];
    AppLocalePicker: typeof import('./src/components/Application/src/AppLocalePicker.vue')['default'];
    AppLogo: typeof import('./src/components/Application/src/AppLogo.vue')['default'];
    AppProvider: typeof import('./src/components/Application/src/AppProvider.vue')['default'];
    AppSearch: typeof import('./src/components/Application/src/search/AppSearch.vue')['default'];
    AppSearchFooter: typeof import('./src/components/Application/src/search/AppSearchFooter.vue')['default'];
    AppSearchKeyItem: typeof import('./src/components/Application/src/search/AppSearchKeyItem.vue')['default'];
    AppSearchModal: typeof import('./src/components/Application/src/search/AppSearchModal.vue')['default'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ATextarea: typeof import('ant-design-vue/es')['Textarea'];
    BasicArrow: typeof import('./src/components/Basic/src/BasicArrow.vue')['default'];
    BasicDrawer: typeof import('./src/components/Drawer/src/BasicDrawer.vue')['default'];
    BasicHelp: typeof import('./src/components/Basic/src/BasicHelp.vue')['default'];
    BasicMenu: typeof import('./src/components/Menu/src/BasicMenu.vue')['default'];
    BasicMenuItem: typeof import('./src/components/Menu/src/components/BasicMenuItem.vue')['default'];
    BasicSubMenuItem: typeof import('./src/components/Menu/src/components/BasicSubMenuItem.vue')['default'];
    BasicTitle: typeof import('./src/components/Basic/src/BasicTitle.vue')['default'];
    CollapseTransition: typeof import('./src/components/Transition/src/CollapseTransition.vue')['default'];
    DrawerFooter: typeof import('./src/components/Drawer/src/components/DrawerFooter.vue')['default'];
    DrawerHeader: typeof import('./src/components/Drawer/src/components/DrawerHeader.vue')['default'];
    Dropdown: typeof import('./src/components/Dropdown/src/Dropdown.vue')['default'];
    Editor: typeof import('./src/components/Tinymce/src/Editor.vue')['default'];
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default'];
    IconPicker: typeof import('./src/components/Icon/src/IconPicker.vue')['default'];
    ImgUpload: typeof import('./src/components/Tinymce/src/ImgUpload.vue')['default'];
    Loading: typeof import('./src/components/Loading/src/Loading.vue')['default'];
    MarkdownViewer: typeof import('./src/components/Markdown/src/MarkdownViewer.vue')['default'];
    Menu: typeof import('./src/components/SimpleMenu/src/components/Menu.vue')['default'];
    MenuCollapseTransition: typeof import('./src/components/SimpleMenu/src/components/MenuCollapseTransition.vue')['default'];
    MenuItem: typeof import('./src/components/SimpleMenu/src/components/MenuItem.vue')['default'];
    MenuItemContent: typeof import('./src/components/Menu/src/components/MenuItemContent.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Scrollbar: typeof import('./src/components/Scrollbar/src/Scrollbar.vue')['default'];
    ScrollContainer: typeof import('./src/components/Container/src/ScrollContainer.vue')['default'];
    SimpleMenu: typeof import('./src/components/SimpleMenu/src/SimpleMenu.vue')['default'];
    SimpleMenuTag: typeof import('./src/components/SimpleMenu/src/SimpleMenuTag.vue')['default'];
    SimpleSubMenu: typeof import('./src/components/SimpleMenu/src/SimpleSubMenu.vue')['default'];
    SubMenuItem: typeof import('./src/components/SimpleMenu/src/components/SubMenuItem.vue')['default'];
    SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default'];
  }
}
