version: "3.9"

services:
  web-portal-setup:
    depends_on:
      - web
    image: ${DOCKER_HUB_USER_NAME}/vblog-setup:${VBLOG_WEB_VERSION}
    tty: true
    command: >
      sh -c "
        if [ -d /usr/share/nginx/html/release/portal ]; then
          rm -rf /usr/share/nginx/html/release/portal;
        fi;
        mkdir /usr/share/nginx/html/release/portal;
        cp -r /data/* /usr/share/nginx/html/release/portal"
    volumes:
      - env-web-data:/usr/share/nginx/html/release
  web-admin-setup:
    image: ${DOCKER_HUB_USER_NAME}/vblog-web-admin-setup:${VBLOG_WEB_ADMIN_VERSION}
    depends_on:
      - web
    command: >
      sh -c "
        if [ -d /usr/share/nginx/html/release/admin ]; then
          rm -rf /usr/share/nginx/html/release/admin;
          echo portal existed;
        fi;
        mkdir /usr/share/nginx/html/release/admin;
        cp -r /data/* /usr/share/nginx/html/release/admin"
    volumes:
      - env-web-data:/usr/share/nginx/html/release
  server-portal:
    image: ${DOCKER_HUB_USER_NAME}/vblog-server-portal:${VBLOG_SERVER_PORTAL_VERSION}
    environment:
      - JASYPT_PASSWORD=${JASYPT_PASSWORD}
    volumes:
      - /data/uploads:/data/uploads
    ports:
      - ${VBLOG_SERVER_PORTAL_PORT}:8889

  server-admin:
    image: ${DOCKER_HUB_USER_NAME}/vblog-server-admin:${VBLOG_SERVER_ADMIN_VERSION}
    environment:
      - JASYPT_PASSWORD=${JASYPT_PASSWORD}
    volumes:
      - /data/uploads:/data/uploads
    ports:
      - ${VBLOG_SERVER_ADMIN_PORT}:8888

volumes:
  es-certs:
    driver: local
  env-web-data:
    external: true
networks:
  env-network:
    external: true
