version: "3.9"

services:
  web-portal-setup:
    image: ${DOCKER_HUB_USER_NAME}/vblog-web:${VBLOG_WEB_VERSION}
    command: >
      sh -c '
        if [ -d /usr/share/nginx/html/release/vblog-web ]; then
          rm -rf /usr/share/nginx/html/release/vblog-web;
        fi;
        mkdir /usr/share/nginx/html/release/vblog-web;
        cp -r /data/* /usr/share/nginx/html/release/vblog-web
      '
    volumes:
      - env_web-data:/usr/share/nginx/html/release
    networks:
      - env-network

  web-admin-setup:
    image: ${DOCKER_HUB_USER_NAME}/vblog-web-admin:${VBLOG_WEB_ADMIN_VERSION}
    command: >
      sh -c '
        if [ -d /usr/share/nginx/html/release/vblog-web-admin ]; then
          rm -rf /usr/share/nginx/html/release/vblog-web-admin;
          echo portal existed;
        fi;
        mkdir /usr/share/nginx/html/release/vblog-web-admin;
        cp -r /data/* /usr/share/nginx/html/release/vblog-web-admin
      '
    volumes:
      - env_web-data:/usr/share/nginx/html/release
    networks:
      - env-network

  web-setup:
    image: nginx:1.23.3-alpine
    volumes:
      - env_nginx-conf:/etc/nginx/conf.d/
      - ./vblog-web-nginx.conf:/vblog-web-nginx.conf
    command: sh -c "cp /vblog-web-nginx.conf /etc/nginx/conf.d/default-locations"
    networks:
      - env-network

  server-admin:
    container_name: vblog-server-admin
    image: ${DOCKER_HUB_USER_NAME}/vblog-server-admin:${VBLOG_SERVER_ADMIN_VERSION}
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - REDIS_SERVER_HOST=${REDIS_SERVER_HOST}
      - MYSQL_SERVER_HOST=${MYSQL_SERVER_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - env-network
    volumes:
      - /projects/public/data/uploads:/projects/public/data/uploads
    ports:
      - ${VBLOG_SERVER_ADMIN_PORT}:8888
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider localhost:8888/actuator/health" ]
      interval: 1s
      timeout: 5s
      retries: 120

  server-portal:
    container_name: vblog-server-portal
    image: ${DOCKER_HUB_USER_NAME}/vblog-server-portal:${VBLOG_SERVER_PORTAL_VERSION}
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - REDIS_SERVER_HOST=${REDIS_SERVER_HOST}
      - MYSQL_SERVER_HOST=${MYSQL_SERVER_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /projects/public/data/uploads:/projects/public/data/uploads
    ports:
      - ${VBLOG_SERVER_PORTAL_PORT}:8889
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider localhost:8889/actuator/health" ]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - env-network

  server-search:
    container_name: vblog-server-search
    image: ${DOCKER_HUB_USER_NAME}/vblog-server-search:${VBLOG_SERVER_SEARCH_VERSION}
    environment:
      - ELASTIC_SERVER_HOST=${ELASTIC_SERVER_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - env_es-certs:/data/elastic
      - /projects/public/data/uploads:/projects/public/data/uploads
    ports:
      - ${VBLOG_SERVER_SEARCH_PORT}:8890
    entrypoint: >
      sh -c '
        cp /data/elastic/ca/ca.crt /opt/openjdk-17/lib/security;
        keytool -import -noprompt -keystore /opt/openjdk-17/lib/security/cacerts -storepass changeit -keypass changeit -alias es01-cas -file /data/elastic/ca/ca.crt
        echo "DONE!"
        java -jar -Dspring.profiles.active=prod /vblog-server-search-0.0.1-SNAPSHOT.jar
        ./
      '
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider localhost:8890/actuator/health" ]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - env-network

  server-setup:
    depends_on:
      server-admin:
        condition: service_healthy
      server-portal:
        condition: service_healthy
      server-search:
        condition: service_healthy
    networks:
      - env-network
    image: nginx:1.23.3-alpine
    volumes:
      - env_nginx-conf:/etc/nginx/conf.d/
      - ./vblog-server-nginx.conf:/vblog-server-nginx.conf
    command: |
      sh -c "
        cp /vblog-server-nginx.conf /etc/nginx/conf.d/default-locations;
        echo down;
        java -jar -Dspring.profiles.active=prod /vblog-server-search-0.0.1-SNAPSHOT.jar
      "

  logstash-setup:
    depends_on:
      - server-search
    image: ${LOGSTASH_IMAGE_NAME}:${LOGSTASH_IMAGE_VERSION}
    user: '0'
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - env_es-certs:/data/elastic
      - env_logstash-pipeline:/usr/share/logstash/pipeline
      - ./elasticsearch/vblog-logstash.conf:/vblog-logstash.conf
      - ./elasticsearch/articles.sh:/articles.sh
    command: >
      bash -c '
        /articles.sh
        cp /vblog-logstash.conf /usr/share/logstash/pipeline/
      '
    networks:
      - env-network

volumes:
  env_es-certs:
    external: true
  env_web-data:
    external: true
  env_logstash-pipeline:
    external: true
  env_nginx-conf:
    external: true

networks:
  env-network:
    external: true
