server:
  port: 8889

spring:
  # 配置redis
  redis:
    database: 3
    port: 6379
    password:
  # 配置mysql数据库
  datasource:
    url: jdbc:mysql://${SERVER_HOST}:3406/vblog-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  # 配置缓存
  cache:
    redis:
      time-to-live: 1d

file:
  upload:
    path: /project/public/data/uploads/  #文件上传目标路径
    baseUrl: http://localhost/uploads/
