server:
  port: 8888

spring:
  # 配置redis
  redis:
    database: 0
    port: 6480
    password:
    host: ${REDIS_SERVER_HOST}
  # 配置mysql数据库
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER_HOST}:3406/vblog?autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  # 配置缓存
  cache:
    redis:
      time-to-live: 1d

#文件配置
file:
  upload:
    path: /projects/public/data/uploads/  #文件上传目标路径
    baseUrl: http://localhost/uploads/
