spring:
  profiles:
    active: dev #默认开发环境
  jackson:
    default-property-inclusion: non_null
  mvc:
    hiddenmethod:
      filter:
        #设置restful风格
        enabled: true
    format:
      #设置日期格式
      date: iso
      date-time: yyyy-MM-dd HH:mm:ss
  elasticsearch:
    username: elastic
    uris: https://${SERVER_HOST}:9200
    password: ${ELASTIC_PASSWORD}

pagehelper:
  pageSizeZero: true

