#file: noinspection YAMLSchemaValidation
name: Deploy Project

on:
  push:
    branches:
     - main

jobs:
  deploy-project:
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        project-name: [ vblog-server-admin, vblog-server-portal, vblog-server-search ]
    with:
      project-name: ${{ matrix.project-name }}
