#file: noinspection YAMLSchemaValidation
name: Deploy

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  check-update:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Check out project update
        run: |
          if [ -n "$(git diff ${{ inputs.project-name }})" ];
          then
            echo "is_update=true" >> $GITHUB_OUTPUT
          fi

  push-to-docker-registry:
    needs: check-update
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ needs.push_to_docker_registry.outputs.is_update == 'true'}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Checkout gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

#      - name: Check project update
#        run: |
#          if [ -n "$(git diff HEAD^ ${{ inputs.project-name }})" ];
#          then
#            echo "is_update=true" >> $GITHUB_OUTPUT
#          fi

      - name: Run build with Gradle wrapper
#        if: ${{ fromJSON(needs.push_to_docker_registry.outputs.is_update) == 'true' }}
        run: |
          ./gradlew :${{ inputs.project-name }}:test;
          ./gradlew :${{ inputs.project-name }}:bootJar;
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.project-name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ inputs.project-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
