#file: noinspection YAMLSchemaValidation
name: Deploy Project

on:
  push:
    branches:
     - main

jobs:
  deploy-project:
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        project-name: [ vblog-server-admin, vblog-server-portal, vblog-server-search ]
    with:
      project-name: ${{ matrix.project-name }}
    secrets:
      server-host: ${{ secrets.SERVER_HOST }}
      mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      jwt-secret: ${{ secrets.JWT_SECRET }}
      elastic-password: ${{ secrets.ELASTIC_PASSWORD }}
      docker-password: ${{ secrets.DOCKER_USERNAME }}
      docker-username: ${{ secrets.DOCKER_PASSWORD }}
