#file: noinspection YAMLSchemaValidation
name: Deploy

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  check-update:
    name: Check if the project is updated
    runs-on: ubuntu-latest
    outputs:
      is_update: ${{ steps.step2.outputs.is_update }}
    steps:
      - id: step1
        name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: step2
        name: Check out project update
        run: |
          if [ -n "$(git diff HEAD^ -- ${{ inputs.project-name }})" ];
          then
            echo "is_update=true" >> $GITHUB_OUTPUT
          fi

  push-to-docker-registry:
    needs: check-update
    name: Build, test and push docker image to docker hub
    runs-on: ubuntu-latest
    if: ${{ needs.check-update.outputs.is_update == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle wrapper
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          MYSQL_ROOT_PASSWORD: ${ secrets.MYSQL_ROOT_PASSWORD }}
          JWT_SECRET: ${ secrets.JWT_SECRET }
          ELASTIC_PASSWORD: ${ secrets.ELASTIC_PASSWORD }
        run: |
          ./gradlew :${{ inputs.project-name }}:test;
          ./gradlew :${{ inputs.project-name }}:bootJar;

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.project-name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ inputs.project-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
