#file: noinspection YAMLSchemaValidation
name: Deploy Project

on:
  push:
    branches:
     - main

jobs:
  deploy-project:
    strategy:
      matrix:
        project-name: [ vblog-server-admin, vblog-server-portal ]
    uses: ./.github/workflows/deploy.yml
    with:
    project-name: ${{ matrix.project-name }}
